version: '3.4'

x-healthcheck: &healthcheck
  test: [ "CMD", "curl", "-sf", "http://127.0.0.1:8545" ]
  interval: 5s
  timeout: 5s
  retries: 3
  start_period: 30s

services:
  verifier:
    image: mantlenetworkio/l2geth:v0.3.2
    entrypoint: sh ./geth.sh
    env_file:
      - ./goerli/envs/geth.env
    volumes:
      - ./data/replica:/root/.ethereum/geth/
    environment:
      ETH1_HTTP: https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
      SEQUENCER_CLIENT_HTTP:  https://rpc-tob.testnet.mantle.xyz
      ROLLUP_STATE_DUMP_PATH: https://mantlenetworkio.github.io/networks/goerli/genesis.json
      ROLLUP_CLIENT_HTTP: https://dtl-tob.testnet.mantle.xyz
      ROLLUP_BACKEND: 'l2'
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      ROLLUP_VERIFIER_ENABLE: 'true'
      ROLLUP_EIGEN_DA_BLOCK: "8280000"
    ports:
      - ${VERIFIER_HTTP_PORT:-8547}:8545
      - ${VERIFIER_WS_PORT:-8548}:8546
    x-healthcheck: *healthcheck